version: '3.8'

services:
  emb-backend:
    build: .
    container_name: emb-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5005:5005"
    volumes:
      # Persister la base de donn√©es SQLite
      - ./database:/app/database
    networks:
      - emb-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  emb-network:
    driver: bridge
